baseURL = "https://theselfhostingblog.com/"
languageCode = "en-us"
title = "The Self-Hosting Blog"
theme = "hugo-blog-awesome"
enableRobotsTXT = true
enableEmoji = true

[pagination]
  pagerSize = 10

[taxonomies]
  tag = "tag"
  author = "author"

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    noClasses = false
    style = "github-dark"

[params]
  sitename = "The Self-Hosting Blog"
  description = "Guides and tutorials on self-hosting, Linux, Docker, and open-source software."
  mainSections = ["posts"]
  defaultColor = "dark"
  toc = true
  tocOpen = false
  goToTop = true
  ShowReadingTime = true
  ShowBreadCrumbs = true
  rssFeedDescription = "summary"

  [params.author]
    name = "Ed"
    intro = "The Self-Hosting Blog"
    description = "Join us and discover the latest in self-hosted applications and other open source technologies. We are two Software Engineers based in the UK, sharing guides on self-hosting, Docker, Linux, and open-source software."

[[params.socialIcons]]
  name = "twitter"
  url = "https://twitter.com/selfhostingblog"

[[params.socialIcons]]
  name = "mastodon"
  url = "https://fosstodon.org/web/accounts/320676"

[[params.socialIcons]]
  name = "Rss"
  url = "/index.xml"

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "Guides"
    url = "/tag/guides/"
    weight = 2
  [[menu.main]]
    name = "Ramblings"
    url = "/tag/ramblings/"
    weight = 3
  [[menu.main]]
    name = "About Us"
    url = "/about-us/"
    weight = 4
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 5

[outputs]
  home = ["HTML", "RSS"]
